using FP.Patterns.State.Exercice4;

AtmMachine atm = new AtmMachine();

Console.WriteLine($"WHEN NO CARD IS INSERTED");
atm.EjectingCard();
atm.EnteringPin();
atm.RequestingCash();
Console.WriteLine($"--------------------------");
Console.WriteLine($"WHEN CARD IS INSERTED THEN EJECTING");
atm.InsertingCard();
atm.EjectingCard();
atm.EnteringPin();
atm.RequestingCash();
Console.WriteLine($"--------------------------");
Console.WriteLine($"WHEN CARD IS INSERTED AND ENTER THE PIN BUT THEN EJECTING");
atm.InsertingCard();
atm.EnteringPin();
atm.EjectingCard();
atm.RequestingCash();
Console.WriteLine($"--------------------------");
Console.WriteLine($"WHEN CARD IS INSERTED AND ENTER THE PIN AND REQUEST CASH AND EJECTING");
atm.InsertingCard();
atm.EnteringPin();
atm.RequestingCash();
atm.EjectingCard();
Console.WriteLine($"--------------------------");
Console.WriteLine($"WHEN CARD IS INSERTED AND ENTER THE PIN AND REQUEST CASH AND EJECTING AND REQUEST MORE CASH ");
atm.InsertingCard();
atm.EnteringPin();
atm.RequestingCash();
atm.EjectingCard();
atm.RequestingCash();
Console.WriteLine($"--------------------------");
Console.WriteLine($"WHEN CARD IS INSERTED AND ENTER THE PIN AND REQUEST CASH AND REQUEST MORE CASH AND EJECTING");
atm.InsertingCard();
atm.EnteringPin();
atm.RequestingCash();
atm.RequestingCash();
atm.EjectingCard();
Console.WriteLine($"--------------------------");